import './style/global.css';
import './style/layout.css';
import './style/responsive.css';
import './style/swiper-custom.css';
import './components/common/buttons/pagination/index.js';
import './components/common/scroll-snap/index.js';
import './pages/home.js';
import './components/calendar/index.js';
import './components/gallery/index.js';
